CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [EmailId] NVARCHAR(50) NOT NULL, 
    [GuidId] NVARCHAR(50) NOT NULL, 
    [SendDate] DATETIME NOT NULL
)
